### ISSUE TITLE
channel order

### ISSUE THREAD

**Issue by guneteroglu** [Emotiv/cortex-example#101]

**Comment by guneteroglu** [comment]
Hello,
In the Community SDK, the order of the channels were AF3, F3, F7,....
In the Cortex SDK, it is AF3,F7,F3,...
Please confirm this change in the new SDK.

**Comment by bchaperon** [comment]
Hi @guneteroglu 

Yes, the order may be different. In Cortex, you should check the result of the method "subscribe" in order to know the exact order of the channels.
https://emotiv.gitbook.io/cortex-api/data-subscription/subscribe
https://emotiv.gitbook.io/cortex-api/data-subscription/data-sample-object
