### ISSUE TITLE
Cannot find OnMentalCommandReceived event

### ISSUE THREAD

**Issue by gunnicus** [Emotiv/cortex-example#175]
Hi, 

I can't find OnMentalCommandReceived event from c# sample, is there a sample how can I detect a "Push" command and do something in the code after receive a "Push" command.

Thanks a lot.

**Comment by tungntEmotiv** [comment]
Hi @gunnicus ,

Not like unity example, C# example hasn't support subscribed 'com' data stream for mental command. But you can modify the code as below to see the 'com' data.

1) Modify the  Training.cs  as below
![image_com](https://user-images.githubusercontent.com/21233798/161472431-bee4b5ab-fde2-4e49-8c02-6b8891c32e2f.png)

![image](https://user-images.githubusercontent.com/21233798/161472445-610121e5-0f1d-452c-823f-fc84a4ecb9c8.png)

2) Run  MentalCommandTraining example. Please note that you have to load a trained profile to see the right  mental command action and power otherwise only return 'neutral'

Please run and let us know the result.
