### ISSUE TITLE
Question: Node JS example and getting an issue. How do I enable logging to see detailed issue  

### ISSUE THREAD

**Issue by pstechfreak** [Emotiv/cortex-example#50]
Operating system: ✍️ WIN 10 Pro language version:(nodejs version) 8.11.4 Cortex version:  Emotiv Pro version 1.5.99  I am trying to run node js example https://github.com/Emotiv/cortex-example/blob/master/nodejs/src/raw.js  and I am getting an error Incorrect user name or password.

**Comment by sberryman** [comment]
@pstechfreak the documentation is really quite awful. This is what I had to do:

Raw example:
1. Visit https://www.emotiv.com/my-account/cortex-apps/
1. Register a new application and record the ClientID and ClientSecret
1. Update the auth object on line 58 of src/raw.js with your username, password and the ClientID and Client Secret from the previous step
1. Download and install the Cortex App from https://www.emotiv.com/developer/
1. Accept the EULA within the Cortex App
1. Run the raw app `node raw.js`

There was also a problem with injectMarker as the timestamp should be number of milliseconds since epoch. So change line 90:

From:
```js
.injectMarker({ label: "key", value: name, time })
```

To:
```js
.injectMarker({ label: "key", value: name, time: time.valueOf() })
```

They don't give you an example of how to consume the markers either. So you'll end up with integer values in your CSV but no way to reference the integer to the actual keypress. The marker data is included in the response to `injectMarker` so you will need to look at the result object which you can obtain by replacing line 91 with:
```js
.then((result) => {
```
After which you'll see marker data in `result.markers`
