### ISSUE TITLE
No way of subscribing to specific profile

### ISSUE THREAD

**Issue by ProjectProgramAMark** [Emotiv/cortex-example#57]
Operating system: MacOS Mojave (10.14.1)
language version: NodeJS
Cortex version: Latest

---

I'm not seeing a specific way to designate a specific profile to use. For instance, if I want to subscribe to "com," I'm not able to set the profile I want to use.

Another issue is that the values of the mental command events are not being returned when subscribing. The response I get when subscribed to "com" is the following:

```
[ { com: { cols: [Array] },
    sid: '1988c0b6-7a95-424d-83a0-87fbcfc69d04' } ]
```

The value of [Array] is simply
`['act', 'pow']`

Just those two strings. The response denoted on the documentation is different in that I am supposed to be getting the mental command action and the power value, but instead I am getting just those two strings.

**Comment by bchaperon** [comment]
Hello @ProjectProgramAMark 

To use an existing profile (created by [EmotivBCI](https://www.emotiv.com/emotiv-bci/) for example) you must call the method "setupProfile", with the status "load".
https://emotiv.github.io/cortex-docs/#setupprofile

The response you receive when you subscribe is correct.
This response just let you know that you subscribed  successfully.
The actual mental command events will then be sent by the server, so you just need to keep listening to new messages from the web socket.

However, you must train a profile and load it first.
The mental command detection cannot work without training.

**Comment by kubaper** [comment]
Hi @ProjectProgramAMark 

I had similar problem with receiving data form stream, and i my case it was wrong type of websocket connection used. I am using python, so i'll present it on python websocket library:
[https://pypi.org/project/websocket-client/](https://pypi.org/project/websocket-client/)
I was using "Short-lived one-off send-receive" example instead of "Long-lived connection"
Maybe your problem is analogous.

**Comment by ProjectProgramAMark** [comment]
@bchaperon that was it, thanks!
