### ISSUE TITLE
Problem "Device session has been closed. Please try again"

### ISSUE THREAD

**Issue by Louislar** [Emotiv/cortex-example#82]
Operating system: win10 edu
Last upstream commit (run git log --author="Robert Lord" | head -n 1):
language version : C#
Cortex version: EmotivPRO v1.8.1

Originally, I can execute EmotivPro and example of cortex-example.
I also meet the same problem with  other opened issues  about "Session limit has been reached... " and "Session does not exisit".
My update request string is 
{ "jsonrpc":"2.0","method":"updateSession","id":1,"params":{ "_auth":"********","status":"active"} }.
Is the request string right?
How to solve this problem?

![issue01](https://user-images.githubusercontent.com/27009338/51671244-6f8ccd00-2003-11e9-886a-d0b0201a5480.PNG)
Thank you!!

**Comment by MichaelaCF** [comment]
Hi @Louislar 
as you have propably read from the other issues, I have a similar (or maybe the same) issue since the last updates. 
What helps me temporarily, it to log out and in at emotivPro. 
You need to make sure you are only logged in at one application. If you want to use emotivPro you need to log out of everything else (or at least disconnect the headset) and vice versa. 
But for the session limit when working with the Cortex API this also works just for one time and then you need to log out or disconnect the headset again manually because it always connects automatically. 

I hope this helps a little! :) 
I am also having contact with the support, because of the session limit and session does not exist, but they seem to just don't get the issue...
